pipeline {
    agent { label 'frontend' }
    environment {
        SERVER_CREDENTIALS = 's3-access'
        WEBHOOK_URL = credentials('DiscordWebhookVT')
        BUCKET = 'vladyslav-team-bucket'
        API_URL = credentials('url_back_vt')
    }
    stages {
        stage('clone') {
            steps {
                git branch: 'dev', url: 'https://github.com/Vladyslav-Team/frontend.git'
            }
        }
        stage('build') {
            steps {
                sh '''
                export REACT_APP_API_URL=${API_URL}
                npm install 
                npm run build
                chmod -R 755 ./build/*
                '''
            }
        }
        stage('deploy') {
            steps {
                sh '''
                    ssh -i "/home/jenkins/.ssh/slave-SoftServe2023" vladyslav-team@172.31.117.224 "rm -rf /var/www/vladyslav-team/html/*"
                    scp -i "/home/jenkins/.ssh/slave-SoftServe2023" -rp ./build/* vladyslav-team@172.31.117.224:/var/www/vladyslav-team/html/
                '''
            }
        }
        stage('upload to s3') {
            steps {
                withAWS(credentials: "${SERVER_CREDENTIALS}", region: 'eu-central-1') {
                    script {
                        println 'Uploading artifacts...'
                        sh '''
                        cd ./build/
                        tar -cvzf "build-${BUILD_NUMBER}.tar.gz" ./*
                        '''
                        s3Upload(file: "./build/build-${BUILD_NUMBER}.tar.gz", bucket: "${BUCKET}", path:"frontend/dev")
                    }
                }
            }
        }
    }
    post {
        always {
            discordSend description: "Jenkins pipeline build: ${currentBuild.currentResult}\nBuild log: ${BUILD_URL}consoleText",
                link: env.BUILD_URL,
                result: currentBuild.currentResult,
                title: JOB_NAME,
                webhookURL: "${env.WEBHOOK_URL}"
            sh 'rm -rf ../*'
        }
    }
}
