pipeline {
    agent none
    environment {
        SERVER_CREDENTIALS = 's3-access'
        WEBHOOK_URL = credentials('DiscordWebhookVT')
        BUCKET = 'vladyslav-team-bucket'
        REGION = 'eu-central-1'
        BACKEND_ACCESS_KEY = 'vt_backend_access_key'
        BACKEND_SECRET_KEY = 'vt_backend_secret_key'
        DATABASE_URL = 'vt_database_url'
        DATABASE_PASSWORD = 'vt_database_password'
    }
    stages {
        stage('Build') {
            agent { label 'java && jdk-17' }
            steps {
                git branch: 'dev', url: 'https://github.com/Vladyslav-Team/backend.git'
                sh '''
                    export JAVA_HOME="/lib/jvm/jdk-17"

                    export BUCKET="vladyslav-team-backend"
                    export S3_ACCESS_KEY=$(aws ssm get-parameter --region ${REGION} --name ${BACKEND_ACCESS_KEY} --with-decryption --query Parameter.Value --output text)
                    export S3_SECRET_KEY=$(aws ssm get-parameter --region ${REGION} --name ${BACKEND_SECRET_KEY} --with-decryption --query Parameter.Value --output text)
                    export S3_REGION=${REGION}

                    export DB_LOGIN="vt"
                    export DB_PASSWORD=$(aws ssm get-parameter --region ${REGION} --name ${DATABASE_PASSWORD} --with-decryption --query Parameter.Value --output text)
                    export DB_URL=$(aws ssm get-parameter --region ${REGION} --name ${DATABASE_URL} --with-decryption --query Parameter.Value --output text)

                    rm -f .env
                    export SPRING_PROFILES_ACTIVE=prod

                    chmod 744 ./mvnw
                    ./mvnw clean package
                    cp ./target/skillscope*.jar ./skillscope-${BUILD_NUMBER}.jar
                '''
                withAWS(credentials: "${SERVER_CREDENTIALS}", region: "${REGION}") {
                    script {
                        s3Upload(file: "./skillscope-${BUILD_NUMBER}.jar", bucket: "${BUCKET}", path:"backend/skillscope-${BUILD_NUMBER}.jar")
                    }
                }
                sh 'rm ./skillscope-${BUILD_NUMBER}.jar'
            }
        }
        stage('Deploy') {
            agent { label 'java && target && dev' }
            steps {
                withAWS(credentials: "${SERVER_CREDENTIALS}", region: "${REGION}") {
                    script {
                        s3Download(file:"./skillscope-${BUILD_NUMBER}.jar", bucket:"${BUCKET}", path:"backend/skillscope-${BUILD_NUMBER}.jar")
                    }
                }
                sh '''
                    sudo systemctl stop skillscope || true
                    chmod 755 ./backend/install-systemd-service.sh
                    ./backend/install-systemd-service.sh
                    mv -f ./skillscope-${BUILD_NUMBER}.jar ~/skillscope.jar
                    sudo systemctl enable skillscope --now
                '''
            }
        }
    }
    post {
        always {
            discordSend description: "Status: `${currentBuild.currentResult}`\nBuild log: ${BUILD_URL}consoleText",
                link: env.BUILD_URL,
                result: currentBuild.currentResult,
                title: JOB_NAME,
                webhookURL: "${env.WEBHOOK_URL}"
        }
    }
}